server:
  port: 8085  # Port du serveur

spring:
  profiles:
    active: dev # Profil actif par défaut

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format-sql: true
  sql:
    init:
      mode: always  # Force l'exécution des scripts SQL
      platform: h2  # Spécifie la plateforme de base de données

geolocation:
  api:
    # key: YOUR_API_KEY
    url: https://nominatim.openstreetmap.org

---
spring:
  config:
    activate:
      on-profile: dev
security:
  enabled: false # Désactiver la sécurité en développement (optionnel)

---
spring:
  config:
    activate:
      on-profile: prod
security:
  enabled: true

