server:
  port: 8085

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

opencv:
  verbose: true
  dnn:
    yolo:
      confidence-threshold: 0.5
      nms-threshold: 0.4
      vehicle-classes: [2, 3, 5, 7] #2: car, 3: moto, 5: bus, 7:track
      mode: darknet
    backend: OPENCV
    target: CPU

video:
  processing:
    timeout: 10000
    max-retries: 3
    error-handling:
      max-conceal-errors: 50
      reset-interval: 60000
  storage:
    path: ../transport-video/src/main/resources/videos
    auto-create-dir: true
  hls:
    output-dir: ../transport-video/target/hls
  ffmpeg:
    probesize: 10000000
    analyzeduration: 5000000
    timeout: 5000
  rtsp:
    timeout: 5000
    buffer-size: 524288
    urls:
      - "rtsp://wesadmin:PiCaM*_*1187@adipappi.media:8554/picamv21"
      - "rtsp://wesadmin:PiCaM*_*1187@adipappi.media:8564/picamv21"

logging:
  level:
    org.bytedeco: INFO
    net.adipappi.transport.api.controllers.video: DEBUG
    net.adipappi.transport.service.video: DEBUG
    net.adipappi.transport.video.service: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
