server:
  port: 8085

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.bytedeco: DEBUG
    net.adipappi.transport.video: TRACE
opencv:
  dnn:
    backend: OPENCV
    target: CPU
    yolo:
      confidence-threshold: 0.5
      nms-threshold: 0.4
      vehicle-classes: [2,3,5,7]  # IDs COCO pour les véhicules
      mode: darknet # ou 'dnn' pour utiliser OpenCV DNN
video:
  processing:
    timeout: 10000 # 10s timeout
    max-retries: 3
  storage:
    path: ../transport-video/src/main/resources/videos
    auto-create-dir: true
  hls:
    output-dir: ../transport-video/target/hls  
  ffmpeg:
    probesize: 10000000
    analyzeduration: 5000000
    timeout: 5000
  rtsp:
    timeout: 5000 # 5s timeout
    buffer-size: 524288 # 512KB buffer
    urls:
      - "rtsp://wesadmin:PiCaM*_*1187@adipappi.media:8554/picamv21"
      - "rtsp://wesadmin:PiCaM*_*1187@adipappi.media:8564/picamv21"

geolocation:
  api:
    url: https://nominatim.openstreetmap.org

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    root: WARN
security:
  enabled: true
